name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20.10.0'
        uses: actions/setup-node@v5
        with:
          node-version: 20.10.0
      - name: Build
        run: npm ci
      - name: Generate OpenAPI Docs
        run: npm run build_openapi_schema
      - name: Check Typescript
        run: npm run ts-check --workspace={frontend,backend}
      - name: Check lint
        run: npm run lint --workspace={frontend,backend}
      - name: Build frontend
        run: npm run build --workspace=frontend
      - name: Build backend
        run: npm run build --workspace=backend
      - name: Execute tests
        run: npm test --workspace=backend
        env:
          CI: true
