name: 'Docker Release build'
on:
    workflow_dispatch: null
    release:
        types:
            - released
env:
    REGISTRY: ghcr.io
jobs:
    info:
        runs-on: ubuntu-latest
        name: 'Get repository information'
        outputs:
            version: '${{ steps.vars.outputs.version }}'
        steps:
            -
                name: Checkout
                uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
                with:
                    repository: knuspel/Congatudo
                    fetch-depth: 0
                    token: '${{ github.token }}'
            -
                name: 'Set up variables'
                id: vars
                run: 'echo "version=$(git describe --abbrev=0 --tags HEAD)" >> $GITHUB_OUTPUT'
    matrix:
        runs-on: ubuntu-latest
        name: 'Get matrix from json'
        outputs:
            matrix: '${{ steps.vars.outputs.matrix }}'
        steps:
            -
                name: Checkout
                uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
            -
                name: 'Set up variables'
                id: vars
                run: 'echo "matrix=$(jq -c . matrix.json)" >> $GITHUB_OUTPUT'
    build:
        runs-on: ubuntu-latest
        name: 'Build for ${{ matrix.image_name }}'
        needs:
            - info
            - matrix
        strategy:
            max-parallel: 2
            matrix: '${{ fromJson(needs.matrix.outputs.matrix) }}'
        steps:
            -
                name: 'Set up QEMU'
                uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
            -
                name: 'Set up Docker Buildx'
                uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
            -
                name: 'Cache Docker layers'
                uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
                with:
                    path: /tmp/.buildx-cache
                    key: '${{ runner.os }}-buildx-${{ matrix.image_name }}-${{ github.sha }}'
                    restore-keys: "${{ runner.os }}-buildx-${{ matrix.image_name }}-\n"
            -
                name: 'Log in to the Container registry'
                uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
                with:
                    registry: '${{ env.REGISTRY }}'
                    username: '${{ github.actor }}'
                    password: '${{ secrets.GITHUB_TOKEN }}'
            -
                name: Build
                uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
                with:
                    push: false
                    load: true
                    tags: "${{ env.REGISTRY }}/knuspel/congatudo:${{ matrix.image_name }}-${{ needs.info.outputs.version }}\n${{ env.REGISTRY }}/knuspel/congatudo:${{ matrix.image_name }}-latest\n"
                    cache-from: 'type=local,src=/tmp/.buildx-cache'
                    cache-to: 'type=local,dest=/tmp/.buildx-cache-new'
                    build-args: "\"BUILD_FROM=${{ matrix.build_from }}\"\n\"PKG_TARGET=${{ matrix.pkg_target }}\"\n\"PKG_OPTIONS=${{ matrix.pkg_options }}\"\n\"BUILD_PLATFORM=${{ matrix.platform }}\"\n"
            -
                name: Push
                run: "docker push ${{ env.REGISTRY }}/knuspel/congatudo:${{ matrix.image_name }}-${{ needs.info.outputs.version }}\ndocker push ${{ env.REGISTRY }}/knuspel/congatudo:${{ matrix.image_name }}-latest\n"
            -
                name: 'Move cache'
                run: "rm -rf /tmp/.buildx-cache\nmv /tmp/.buildx-cache-new /tmp/.buildx-cache\n"
    manifest:
        runs-on: ubuntu-latest
        name: 'Create and push manifest'
        needs:
            - info
            - build
        steps:
            -
                name: 'Set up Docker Buildx'
                uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
            -
                name: 'Log in to the Container registry'
                uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
                with:
                    registry: '${{ env.REGISTRY }}'
                    username: '${{ github.actor }}'
                    password: '${{ secrets.GITHUB_TOKEN }}'
            -
                name: 'Create manifest'
                run: "docker manifest create ${{ env.REGISTRY }}/knuspel/congatudo:alpine-latest \\\n  --amend ${{ env.REGISTRY }}/knuspel/congatudo:alpine-armv7-latest \\\n  --amend ${{ env.REGISTRY }}/knuspel/congatudo:alpine-aarch64-latest \\\n  --amend ${{ env.REGISTRY }}/knuspel/congatudo:alpine-amd64-latest\ndocker manifest create ${{ env.REGISTRY }}/knuspel/congatudo:homeassistant-latest \\\n  --amend ${{ env.REGISTRY }}/knuspel/congatudo:homeassistant-armhf-latest \\\n  --amend ${{ env.REGISTRY }}/knuspel/congatudo:homeassistant-armv7-latest \\\n  --amend ${{ env.REGISTRY }}/knuspel/congatudo:homeassistant-aarch64-latest \\\n  --amend ${{ env.REGISTRY }}/knuspel/congatudo:homeassistant-amd64-latest\ndocker manifest create ${{ env.REGISTRY }}/knuspel/congatudo:alpine-${{ needs.info.outputs.version }} \\\n  --amend ${{ env.REGISTRY }}/knuspel/congatudo:alpine-armv7-${{ needs.info.outputs.version }} \\\n  --amend ${{ env.REGISTRY }}/knuspel/congatudo:alpine-aarch64-${{ needs.info.outputs.version }} \\\n  --amend ${{ env.REGISTRY }}/knuspel/congatudo:alpine-amd64-${{ needs.info.outputs.version }}\ndocker manifest create ${{ env.REGISTRY }}/knuspel/congatudo:homeassistant-${{ needs.info.outputs.version }} \\\n  --amend ${{ env.REGISTRY }}/knuspel/congatudo:homeassistant-armhf-${{ needs.info.outputs.version }} \\\n  --amend ${{ env.REGISTRY }}/knuspel/congatudo:homeassistant-armv7-${{ needs.info.outputs.version }} \\\n  --amend ${{ env.REGISTRY }}/knuspel/congatudo:homeassistant-aarch64-${{ needs.info.outputs.version }} \\\n  --amend ${{ env.REGISTRY }}/knuspel/congatudo:homeassistant-amd64-${{ needs.info.outputs.version }}\n"
            -
                name: 'Push manifest'
                run: "docker manifest push ${{ env.REGISTRY }}/knuspel/congatudo:alpine-latest\ndocker manifest push ${{ env.REGISTRY }}/knuspel/congatudo:homeassistant-latest\ndocker manifest push ${{ env.REGISTRY }}/knuspel/congatudo:alpine-${{ needs.info.outputs.version }}\ndocker manifest push ${{ env.REGISTRY }}/knuspel/congatudo:homeassistant-${{ needs.info.outputs.version }}\n"
